### ISSUE TITLE
[Bug] Actual package required

### ISSUE THREAD

**Issue by CountOmega** [kpcyrd/cargo-debstatus#12]
I am running the latest cargo debstatus on testing for [rnote](https://github.com/flxzt/rnote). The expected behavior would be t
for it run as usual. Instead, I get the following error:
```
cargo debstatus
Error: this command requires running against an actual package in this workspace

```
It worked fine before for other packages. I don't know what the root cause is here.

Cheers

**Comment by kpcyrd** [comment]
It's because the root Cargo.toml doesn't define a crate, only the workspace:
```toml
[workspace]
members = [
    "rnote-compose",
    "rnote-engine",
    "rnote-ui",
    "rnote-fileformats",
]
exclude = [ "./piet" ]


[profile.dev]
opt-level = 2
debug = true

[profile.release]
opt-level = 3
```

The main crate seems to be in `rnote-ui/`, running it from that subfolder works for me. :)
